version: '3'

services:
  web:
    restart: always
    build:
      context: .
      # dockerfile: Dockerfile-web
    networks:
      - default
      - p1_net
    ports:
      - "5050:5050"
    container_name: web


networks:
  p1_net:
    driver: bridge